# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
   docker:
               - image: circleci/node:6
                 environment:
                     CHROME_BIN: "/usr/bin/google-chrome"
           steps:
               - checkout
               - run:
                   name: Install yarn
                   command: sudo npm install -g yarn
               - restore_cache:
                   key: dependency-cache-{{ checksum "package.json" }}
               - run:
                   name: Install node_modules with yarn
                   command: yarn
               - save_cache:
                   key: dependency-cache-{{ checksum "package.json" }}
                   paths:
                       - ./node_modules
               - run:
                   name: Run unit tests with karma
                   command: yarn test-single-headless
               - store_test_results:
                   path: test-results.xml
      # run tests!
      - run: yarn test


